### ISSUE TITLE
resource (group) is not recreated after manually deleted

### ISSUE THREAD

**Issue by daviduash** [nsofnetworks/terraform-provider-pfptmeta#30] opened 2022-05-16 11:58 UTC
Hey 
I tried to use the terraform provider and got few issues 
1) when try to use the resource 
resource "pfptmeta_network_element" "mapped-service" {
   name           = "mapped service rde"
   mapped_service = "rde.my.domain"
 }
i got the error "│ Error: PATCH request to https://api.metanetworks.com/v1/network_elements/ne-1636 failed with status code 400: Bad Request - Bad request: Disable/enable is not supported for mapped services"

2) i created a group using terraform and then deleted the group from the ui, ever since , the terraform is stuck, i cant run plan to destroy
I get the error "│ Error: GET request to https://api.metanetworks.com/v1/network_elements/ne-1636?expand=true failed with status code 404: Not Found - network element (ne-1636) not found"

@hod-alpert

**Comment by hod-alpert** [comment] 2022-05-16 12:34
Hi @daviduash Regarding 1 - it seems like a bug in the provider, will fix it.
Regarding 2: Once you create a resource from tf it's best to manage it only from tf.
The tf .state file is not aware of the deletion and that's why its failing.
You can try `terraform state rm <resource>` and rerun to solve this.

**Comment by hod-alpert** [comment] 2022-05-17 08:22
Got you.
So about 1: it will be fixed later today.
About 2: this is not a bug, it's a feature request, we'll solve that too, but it will take more time.

**Comment by daviduash** [comment] 2022-05-17 08:23
thank you very much

**Comment by hod-alpert** [comment] 2022-05-17 16:37
@daviduash 1 is fixed with version 0.1.23

**Comment by hod-alpert** [comment] 2022-05-24 07:17
@daviduash 2 is now fixed too in version 0.1.24, enjoy!

**Closed by hod-alpert** 2022-05-24 07:17 UTC
